### PR TITLE
Happ health list

### PR DESCRIPTION
**Pull request by JettTech**
> Pairs with [net-stats-daemon](https://github.com/Holo-Host/net-stats-daemon) PR [#4](https://github.com/Holo-Host/net-stats-daemon/pull/4). 
### Updates:
 - updates `host/stats` endpoint with `hpos_app_list` data

### CODE REVIEW

**Comment by alastairong** [comment]
Sorry accidentally closed wrong PR

**Review by peeech — CHANGES_REQUESTED** [review]
Clean and simple. Just one warning cleanup requested in main.rs:
```
warning: unused import: `mongodb::bson`
 --> src/main.rs:1:5
  |
1 | use mongodb::bson;
  |     ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

**Comment by peeech** [comment]
Also tests need to be updated to new format of `HostStats`. I think that it would be great to use fairly complex `hpos_app_list` which would be passing a type check for a type `Option<HashMap<InstalledAppId, AppStatusFilter>>`

**Review by peeech — APPROVED** [review]
What I am seeing that a newly created field `hpos_app_list` is recorded in db but none of the GET endpoints is making use of it. I think it is fine, because `hpos_app_list` is gonna be used in data postprocessing.

**Pull request merged**
